using System;
using System.Collections.Generic;
using Sirius.Engine;

public class Chara
{
    public Sprite Sprite;
    public Position Position;
    public char C;
    public CharaType CharaType;

    public Chara(char c, byte color, CharaType charaType = CharaType.Ja)
    {
        C = c;
        Position = new Position();
        CharaType = charaType;
        if (CharaType == CharaType.Ja)
        {
            Sprite = new Sprite($"{TextPathJa2[c]}.png", true);
        }
        else
        {
            Sprite = new Sprite($"{TextPathEn[c]}.png", true);
        }
        Sprite.Position.Parent = Position;
        SetColor(color);
    }

    public void Initialize(char c, byte color)
    {
        C = c;
        SetColor(color);
    }

    public void SetColor(byte color)
    {
        for (var i = 0; i < Sprite.Buffer.Length; i++)
        {
            if (Sprite.Buffer[i] == 255)
            {
                continue;
            }

            Sprite.Buffer[i] = color;
        }
    }

    public void Draw()
    {
        Sprite.Draw();
    }

    public static void Initialize()
    {
        TextPathJa2 = new Dictionary<char, string>
        {
            { 'あ', "Text/Ja2/あ" },
            { 'い', "Text/Ja2/い" },
            { 'う', "Text/Ja2/う" },
            { 'え', "Text/Ja2/え" },
            { 'お', "Text/Ja2/お" },
            { 'か', "Text/Ja2/か" },
            { 'き', "Text/Ja2/き" },
            { 'く', "Text/Ja2/く" },
            { 'け', "Text/Ja2/け" },
            { 'こ', "Text/Ja2/こ" },
            { 'が', "Text/Ja2/か" },
            { 'ぎ', "Text/Ja2/き" },
            { 'ぐ', "Text/Ja2/く" },
            { 'げ', "Text/Ja2/け" },
            { 'ご', "Text/Ja2/こ" },
            { 'さ', "Text/Ja2/さ" },
            { 'し', "Text/Ja2/し" },
            { 'す', "Text/Ja2/す" },
            { 'せ', "Text/Ja2/せ" },
            { 'そ', "Text/Ja2/そ" },
            { 'た', "Text/Ja2/た" },
            { 'ち', "Text/Ja2/ち" },
            { 'つ', "Text/Ja2/つ" },
            { 'て', "Text/Ja2/て" },
            { 'と', "Text/Ja2/と" },
            { 'ざ', "Text/Ja2/さ" },
            { 'じ', "Text/Ja2/し" },
            { 'ず', "Text/Ja2/す" },
            { 'ぜ', "Text/Ja2/せ" },
            { 'ぞ', "Text/Ja2/そ" },
            { 'だ', "Text/Ja2/た" },
            { 'ぢ', "Text/Ja2/ち" },
            { 'づ', "Text/Ja2/つ" },
            { 'で', "Text/Ja2/て" },
            { 'ど', "Text/Ja2/と" },
            { 'な', "Text/Ja2/な" },
            { 'に', "Text/Ja2/に" },
            { 'ぬ', "Text/Ja2/ぬ" },
            { 'ね', "Text/Ja2/ね" },
            { 'の', "Text/Ja2/の" },
            { 'は', "Text/Ja2/は" },
            { 'ひ', "Text/Ja2/ひ" },
            { 'ふ', "Text/Ja2/ふ" },
            { 'へ', "Text/Ja2/へ" },
            { 'ほ', "Text/Ja2/ほ" },
            { 'ば', "Text/Ja2/は" },
            { 'び', "Text/Ja2/ひ" },
            { 'ぶ', "Text/Ja2/ふ" },
            { 'べ', "Text/Ja2/へ" },
            { 'ぼ', "Text/Ja2/ほ" },
            { 'ぱ', "Text/Ja2/は" },
            { 'ぴ', "Text/Ja2/ひ" },
            { 'ぷ', "Text/Ja2/ふ" },
            { 'ぺ', "Text/Ja2/へ" },
            { 'ぽ', "Text/Ja2/ほ" },
            { 'ま', "Text/Ja2/ま" },
            { 'み', "Text/Ja2/み" },
            { 'む', "Text/Ja2/む" },
            { 'め', "Text/Ja2/め" },
            { 'も', "Text/Ja2/も" },
            { 'や', "Text/Ja2/や" },
            { 'ゆ', "Text/Ja2/ゆ" },
            { 'よ', "Text/Ja2/よ" },
            { 'ら', "Text/Ja2/ら" },
            { 'り', "Text/Ja2/り" },
            { 'る', "Text/Ja2/る" },
            { 'れ', "Text/Ja2/れ" },
            { 'ろ', "Text/Ja2/ろ" },
            { 'わ', "Text/Ja2/わ" },
            { 'を', "Text/Ja2/を" },
            { 'ん', "Text/Ja2/ん" },
            { 'ぁ', "Text/Ja2/ぁ" },
            { 'ぃ', "Text/Ja2/ぃ" },
            { 'ぅ', "Text/Ja2/ぅ" },
            { 'ぇ', "Text/Ja2/ぇ" },
            { 'ぉ', "Text/Ja2/ぉ" },
            { 'ゃ', "Text/Ja2/ゃ" },
            { 'ゅ', "Text/Ja2/ゅ" },
            { 'ょ', "Text/Ja2/ょ" },
            { 'っ', "Text/Ja2/っ" },
            { 'ア', "Text/Ja2/ア" },
            { 'イ', "Text/Ja2/イ" },
            { 'ウ', "Text/Ja2/ウ" },
            { 'エ', "Text/Ja2/エ" },
            { 'オ', "Text/Ja2/オ" },
            { 'カ', "Text/Ja2/カ" },
            { 'キ', "Text/Ja2/キ" },
            { 'ク', "Text/Ja2/ク" },
            { 'ケ', "Text/Ja2/ケ" },
            { 'コ', "Text/Ja2/コ" },
            { 'ガ', "Text/Ja2/カ" },
            { 'ギ', "Text/Ja2/キ" },
            { 'グ', "Text/Ja2/ク" },
            { 'ゲ', "Text/Ja2/ケ" },
            { 'ゴ', "Text/Ja2/コ" },
            { 'サ', "Text/Ja2/サ" },
            { 'シ', "Text/Ja2/シ" },
            { 'ス', "Text/Ja2/ス" },
            { 'セ', "Text/Ja2/セ" },
            { 'ソ', "Text/Ja2/ソ" },
            { 'タ', "Text/Ja2/タ" },
            { 'チ', "Text/Ja2/チ" },
            { 'ツ', "Text/Ja2/ツ" },
            { 'テ', "Text/Ja2/テ" },
            { 'ト', "Text/Ja2/ト" },
            { 'ザ', "Text/Ja2/サ" },
            { 'ジ', "Text/Ja2/シ" },
            { 'ズ', "Text/Ja2/ス" },
            { 'ゼ', "Text/Ja2/セ" },
            { 'ゾ', "Text/Ja2/ソ" },
            { 'ダ', "Text/Ja2/タ" },
            { 'ヂ', "Text/Ja2/チ" },
            { 'ヅ', "Text/Ja2/ツ" },
            { 'デ', "Text/Ja2/テ" },
            { 'ド', "Text/Ja2/ト" },
            { 'ナ', "Text/Ja2/ナ" },
            { 'ニ', "Text/Ja2/ニ" },
            { 'ヌ', "Text/Ja2/ヌ" },
            { 'ネ', "Text/Ja2/ネ" },
            { 'ノ', "Text/Ja2/ノ" },
            { 'ハ', "Text/Ja2/ハ" },
            { 'ヒ', "Text/Ja2/ヒ" },
            { 'フ', "Text/Ja2/フ" },
            { 'ヘ', "Text/Ja2/ヘ" },
            { 'ホ', "Text/Ja2/ホ" },
            { 'バ', "Text/Ja2/ハ" },
            { 'ビ', "Text/Ja2/ヒ" },
            { 'ブ', "Text/Ja2/フ" },
            { 'ベ', "Text/Ja2/ヘ" },
            { 'ボ', "Text/Ja2/ホ" },
            { 'パ', "Text/Ja2/ハ" },
            { 'ピ', "Text/Ja2/ヒ" },
            { 'プ', "Text/Ja2/フ" },
            { 'ペ', "Text/Ja2/ヘ" },
            { 'ポ', "Text/Ja2/ホ" },
            { 'マ', "Text/Ja2/マ" },
            { 'ミ', "Text/Ja2/ミ" },
            { 'ム', "Text/Ja2/ム" },
            { 'メ', "Text/Ja2/メ" },
            { 'モ', "Text/Ja2/モ" },
            { 'ヤ', "Text/Ja2/ヤ" },
            { 'ユ', "Text/Ja2/ユ" },
            { 'ヨ', "Text/Ja2/ヨ" },
            { 'ラ', "Text/Ja2/ラ" },
            { 'リ', "Text/Ja2/リ" },
            { 'ル', "Text/Ja2/ル" },
            { 'レ', "Text/Ja2/レ" },
            { 'ロ', "Text/Ja2/ロ" },
            { 'ワ', "Text/Ja2/ワ" },
            { 'ヲ', "Text/Ja2/ヲ" },
            { 'ン', "Text/Ja2/ン" },
            { 'ァ', "Text/Ja2/ァ" },
            { 'ィ', "Text/Ja2/ィ" },
            { 'ゥ', "Text/Ja2/ゥ" },
            { 'ェ', "Text/Ja2/ェ" },
            { 'ォ', "Text/Ja2/ォ" },
            { 'ャ', "Text/Ja2/ャ" },
            { 'ュ', "Text/Ja2/ュ" },
            { 'ョ', "Text/Ja2/ョ" },
            { 'ッ', "Text/Ja2/ッ" },
            { 'a', "Text/Ja2/a" },
            { 'b', "Text/Ja2/b" },
            { 'c', "Text/Ja2/c" },
            { 'd', "Text/Ja2/d" },
            { 'e', "Text/Ja2/e" },
            { 'f', "Text/Ja2/f" },
            { 'g', "Text/Ja2/g" },
            { 'h', "Text/Ja2/h" },
            { 'i', "Text/Ja2/i" },
            { 'j', "Text/Ja2/j" },
            { 'k', "Text/Ja2/k" },
            { 'l', "Text/Ja2/l" },
            { 'm', "Text/Ja2/m" },
            { 'n', "Text/Ja2/n" },
            { 'o', "Text/Ja2/o" },
            { 'p', "Text/Ja2/p" },
            { 'q', "Text/Ja2/q" },
            { 'r', "Text/Ja2/r" },
            { 's', "Text/Ja2/s" },
            { 't', "Text/Ja2/t" },
            { 'u', "Text/Ja2/u" },
            { 'v', "Text/Ja2/v" },
            { 'w', "Text/Ja2/w" },
            { 'x', "Text/Ja2/x" },
            { 'y', "Text/Ja2/y" },
            { 'z', "Text/Ja2/z" },
            { 'A', "Text/Ja2/a" },
            { 'B', "Text/Ja2/b" },
            { 'C', "Text/Ja2/c" },
            { 'D', "Text/Ja2/d" },
            { 'E', "Text/Ja2/e" },
            { 'F', "Text/Ja2/f" },
            { 'G', "Text/Ja2/g" },
            { 'H', "Text/Ja2/h" },
            { 'I', "Text/Ja2/i" },
            { 'J', "Text/Ja2/j" },
            { 'K', "Text/Ja2/k" },
            { 'L', "Text/Ja2/l" },
            { 'M', "Text/Ja2/m" },
            { 'N', "Text/Ja2/n" },
            { 'O', "Text/Ja2/o" },
            { 'P', "Text/Ja2/p" },
            { 'Q', "Text/Ja2/q" },
            { 'R', "Text/Ja2/r" },
            { 'S', "Text/Ja2/s" },
            { 'T', "Text/Ja2/t" },
            { 'U', "Text/Ja2/u" },
            { 'V', "Text/Ja2/v" },
            { 'W', "Text/Ja2/w" },
            { 'X', "Text/Ja2/x" },
            { 'Y', "Text/Ja2/y" },
            { 'Z', "Text/Ja2/z" },
            { '+', "Text/Ja2/＋" },
            { '-', "Text/Ja2/ー" },
            { '#', "Text/Ja2/＃" },
            { '%', "Text/Ja2/％" },
            { '/', "Text/Ja2/／" },
            { '\\', "Text/Ja2/＼" },
            { '*', "Text/Ja2/＊" },
            { '[', "Text/Ja2/[" },
            { ']', "Text/Ja2/]" },
            { '、', "Text/Ja2/、" },
            { '。', "Text/Ja2/。" },
            { '.', "Text/Ja2/dot" },
            { '！', "Text/Ja2/！" },
            { '？', "Text/Ja2/？" },
            { '!', "Text/Ja2/！" },
            { '?', "Text/Ja2/？" },
            { '＊', "Text/Ja2/＊" },
            { '>', "Text/Ja2/arrow_right" },
            { '<', "Text/Ja2/arrow_left" },
            { '▽', "Text/Ja2/arrow_down" },
            { '▼', "Text/Ja2/arrow_down" },
            { '▶', "Text/Ja2/arrow_right" },
            { '◀', "Text/Ja2/arrow_left" },
            { '▷', "Text/Ja2/arrow_right" },
            { '◁', "Text/Ja2/arrow_left" },
            { '0', "Text/Ja2/0" },
            { '1', "Text/Ja2/1" },
            { '2', "Text/Ja2/2" },
            { '3', "Text/Ja2/3" },
            { '4', "Text/Ja2/4" },
            { '5', "Text/Ja2/5" },
            { '6', "Text/Ja2/6" },
            { '7', "Text/Ja2/7" },
            { '8', "Text/Ja2/8" },
            { '9', "Text/Ja2/9" },
            { '０', "Text/Ja2/0" },
            { '１', "Text/Ja2/1" },
            { '２', "Text/Ja2/2" },
            { '３', "Text/Ja2/3" },
            { '４', "Text/Ja2/4" },
            { '５', "Text/Ja2/5" },
            { '６', "Text/Ja2/6" },
            { '７', "Text/Ja2/7" },
            { '８', "Text/Ja2/8" },
            { '９', "Text/Ja2/9" },
            { '～', "Text/Ja2/～" },
            { 'ー', "Text/Ja2/ー" },
            { '　', "Text/Ja2/space" },
            { ' ', "Text/Ja2/space" },
            { '゙', "Text/Ja2/dakuten" },
            { '゚', "Text/Ja2/handakuten" },
            { '゛', "Text/Ja2/dakuten" },
            { '゜', "Text/Ja2/handakuten" },
            { '‥', "Text/Ja2/‥" },
            { '…', "Text/Ja2/‥" },
        };
        
        TextPathEn = new Dictionary<char, string>
        {
            { 'a', "Text/Alpha/text_a" },
            { 'b', "Text/Alpha/text_b" },
            { 'c', "Text/Alpha/text_c" },
            { 'd', "Text/Alpha/text_d" },
            { 'e', "Text/Alpha/text_e" },
            { 'f', "Text/Alpha/text_f" },
            { 'g', "Text/Alpha/text_g" },
            { 'h', "Text/Alpha/text_h" },
            { 'i', "Text/Alpha/text_i" },
            { 'j', "Text/Alpha/text_j" },
            { 'k', "Text/Alpha/text_k" },
            { 'l', "Text/Alpha/text_l" },
            { 'm', "Text/Alpha/text_m" },
            { 'n', "Text/Alpha/text_n" },
            { 'o', "Text/Alpha/text_o" },
            { 'p', "Text/Alpha/text_p" },
            { 'q', "Text/Alpha/text_q" },
            { 'r', "Text/Alpha/text_r" },
            { 's', "Text/Alpha/text_s" },
            { 't', "Text/Alpha/text_t" },
            { 'u', "Text/Alpha/text_u" },
            { 'v', "Text/Alpha/text_v" },
            { 'w', "Text/Alpha/text_w" },
            { 'x', "Text/Alpha/text_x" },
            { 'y', "Text/Alpha/text_y" },
            { 'z', "Text/Alpha/text_z" },
            { 'A', "Text/Alpha/text_a" },
            { 'B', "Text/Alpha/text_b" },
            { 'C', "Text/Alpha/text_c" },
            { 'D', "Text/Alpha/text_d" },
            { 'E', "Text/Alpha/text_e" },
            { 'F', "Text/Alpha/text_f" },
            { 'G', "Text/Alpha/text_g" },
            { 'H', "Text/Alpha/text_h" },
            { 'I', "Text/Alpha/text_i" },
            { 'J', "Text/Alpha/text_j" },
            { 'K', "Text/Alpha/text_k" },
            { 'L', "Text/Alpha/text_l" },
            { 'M', "Text/Alpha/text_m" },
            { 'N', "Text/Alpha/text_n" },
            { 'O', "Text/Alpha/text_o" },
            { 'P', "Text/Alpha/text_p" },
            { 'Q', "Text/Alpha/text_q" },
            { 'R', "Text/Alpha/text_r" },
            { 'S', "Text/Alpha/text_s" },
            { 'T', "Text/Alpha/text_t" },
            { 'U', "Text/Alpha/text_u" },
            { 'V', "Text/Alpha/text_v" },
            { 'W', "Text/Alpha/text_w" },
            { 'X', "Text/Alpha/text_x" },
            { 'Y', "Text/Alpha/text_y" },
            { 'Z', "Text/Alpha/text_z" },
            { '+', "Text/Alpha/text_plus" },
            { '-', "Text/Alpha/text_minus" },
            { '.', "Text/Alpha/text_dot" },
            { '>', "Text/Alpha/text_arrow_r" },
            { '<', "Text/Alpha/text_arrow_l" },
            { '▶', "Text/Alpha/text_arrow_r" },
            { '◀', "Text/Alpha/text_arrow_l" },
            { '▷', "Text/Alpha/text_arrow_r" },
            { '◁', "Text/Alpha/text_arrow_l" },
            { '0', "Text/Alpha/text_0" },
            { '1', "Text/Alpha/text_1" },
            { '2', "Text/Alpha/text_2" },
            { '3', "Text/Alpha/text_3" },
            { '4', "Text/Alpha/text_4" },
            { '5', "Text/Alpha/text_5" },
            { '6', "Text/Alpha/text_6" },
            { '7', "Text/Alpha/text_7" },
            { '8', "Text/Alpha/text_8" },
            { '9', "Text/Alpha/text_9" },
            { '０', "Text/Alpha/text_0" },
            { '１', "Text/Alpha/text_1" },
            { '２', "Text/Alpha/text_2" },
            { '３', "Text/Alpha/text_3" },
            { '４', "Text/Alpha/text_4" },
            { '５', "Text/Alpha/text_5" },
            { '６', "Text/Alpha/text_6" },
            { '７', "Text/Alpha/text_7" },
            { '８', "Text/Alpha/text_8" },
            { '９', "Text/Alpha/text_9" },
            { 'ー', "Text/Alpha/text_minus" },
            { '　', "Text/Alpha/text_space" },
            { ' ', "Text/Alpha/text_space" },
            { '/', "Text/Alpha/text_slash" },
        };
    }

    public static Dictionary<char, string> TextPathJa2;
    public static Dictionary<char, string> TextPathEn;

    public static readonly string Dakuten =
        "がぎぐげござじずぜぞだぢづでどばびぶべぼゔガギグゲゴザジズゼゾダヂヅデドバビブベボ";

    public static readonly string HanDakuten = "ぱぴぷぺぽパピプペポ";
}